### ISSUE TITLE
Change image in chart to be `registry.k8s.io/coredns/coredns`

### ISSUE THREAD

**Issue by onedr0p** [coredns/helm#125]
Hi 👋🏼 

It was be great if the image could be defaulted to the `registry.k8s.io/coredns/coredns` registry instead of Dockerhub.

**Comment by hagaibarel** [comment]
Hi,

The upstream `coredns` project publishes its images to docker hub under `coredns/coredns`, I believe that `registry.k8s.io/coredns/coredns` is a mirror of that. 

Since `coredns` isn't affiliated to kubernetes (although used there ofc) I see no reason to change the default image repository.

You can always set the image and tag to a different value using the chart value file or using command line flags, e.g. `--set image.repository=registry.k8s.io/coredns/coredns --set image.tag=v1.10.1`

**Comment by onedr0p** [comment]
I'd love to see this using a registry outside dockerhub because of how hostile Docker Inc. and Mirantis have been towards the FOSS community.

**Comment by hagaibarel** [comment]
I suggest you open an issue with https://github.com/coredns/coredns/, once it's changed upstream we'll align the chart accordingly
